// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddExternalLink(arg1, arg2) {
  return window['go']['main']['App']['AddExternalLink'](arg1, arg2);
}

export function AddFiles() {
  return window['go']['main']['App']['AddFiles']();
}

export function AddFolder() {
  return window['go']['main']['App']['AddFolder']();
}

export function AddPodcastFiles() {
  return window['go']['main']['App']['AddPodcastFiles']();
}

export function AddPodcastFolder() {
  return window['go']['main']['App']['AddPodcastFolder']();
}

export function Bootstrap() {
  return window['go']['main']['App']['Bootstrap']();
}

export function CancelExternalDownload(arg1) {
  return window['go']['main']['App']['CancelExternalDownload'](arg1);
}

export function ChooseDirectory(arg1) {
  return window['go']['main']['App']['ChooseDirectory'](arg1);
}

export function ChooseFile(arg1, arg2) {
  return window['go']['main']['App']['ChooseFile'](arg1, arg2);
}

export function DebugReindexLibrary() {
  return window['go']['main']['App']['DebugReindexLibrary']();
}

export function DeleteExternalItem(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteExternalItem'](arg1, arg2, arg3);
}

export function DeleteSavedMusicRay(arg1) {
  return window['go']['main']['App']['DeleteSavedMusicRay'](arg1);
}

export function DoctorCheck(arg1, arg2) {
  return window['go']['main']['App']['DoctorCheck'](arg1, arg2);
}

export function DoctorRepair(arg1, arg2) {
  return window['go']['main']['App']['DoctorRepair'](arg1, arg2);
}

export function GetCurrentEmoFlow() {
  return window['go']['main']['App']['GetCurrentEmoFlow']();
}

export function GetExternalMediaSettings() {
  return window['go']['main']['App']['GetExternalMediaSettings']();
}

export function GetPlaybackState() {
  return window['go']['main']['App']['GetPlaybackState']();
}

export function GetRayBuildState() {
  return window['go']['main']['App']['GetRayBuildState']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ImportPaths(arg1) {
  return window['go']['main']['App']['ImportPaths'](arg1);
}

export function ImportPodcastPaths(arg1) {
  return window['go']['main']['App']['ImportPodcastPaths'](arg1);
}

export function ListExternalDownloadJobs(arg1) {
  return window['go']['main']['App']['ListExternalDownloadJobs'](arg1);
}

export function MovePodcastRayItem(arg1, arg2) {
  return window['go']['main']['App']['MovePodcastRayItem'](arg1, arg2);
}

export function MoveQueueItem(arg1, arg2) {
  return window['go']['main']['App']['MoveQueueItem'](arg1, arg2);
}

export function NextPodcast() {
  return window['go']['main']['App']['NextPodcast']();
}

export function NextTrack() {
  return window['go']['main']['App']['NextTrack']();
}

export function OpenExternalSource(arg1) {
  return window['go']['main']['App']['OpenExternalSource'](arg1);
}

export function OpenPodcastRayHistory(arg1) {
  return window['go']['main']['App']['OpenPodcastRayHistory'](arg1);
}

export function PlayPodcast(arg1) {
  return window['go']['main']['App']['PlayPodcast'](arg1);
}

export function PlayPodcastRayItem(arg1) {
  return window['go']['main']['App']['PlayPodcastRayItem'](arg1);
}

export function PlayTrack(arg1) {
  return window['go']['main']['App']['PlayTrack'](arg1);
}

export function PlayTrackWithMode(arg1, arg2) {
  return window['go']['main']['App']['PlayTrackWithMode'](arg1, arg2);
}

export function PreviousPodcast() {
  return window['go']['main']['App']['PreviousPodcast']();
}

export function PreviousTrack() {
  return window['go']['main']['App']['PreviousTrack']();
}

export function RayAudit(arg1, arg2, arg3) {
  return window['go']['main']['App']['RayAudit'](arg1, arg2, arg3);
}

export function RemoveFromQueue(arg1) {
  return window['go']['main']['App']['RemoveFromQueue'](arg1);
}

export function RemovePodcastRayItem(arg1) {
  return window['go']['main']['App']['RemovePodcastRayItem'](arg1);
}

export function ResumeRay(arg1) {
  return window['go']['main']['App']['ResumeRay'](arg1);
}

export function ResumeSavedMusicRay(arg1) {
  return window['go']['main']['App']['ResumeSavedMusicRay'](arg1);
}

export function RetryExternalDownload(arg1) {
  return window['go']['main']['App']['RetryExternalDownload'](arg1);
}

export function RunReclusterSingleflight() {
  return window['go']['main']['App']['RunReclusterSingleflight']();
}

export function SaveExternalMediaSettings(arg1) {
  return window['go']['main']['App']['SaveExternalMediaSettings'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function ScheduleRecluster() {
  return window['go']['main']['App']['ScheduleRecluster']();
}

export function SearchPodcasts(arg1) {
  return window['go']['main']['App']['SearchPodcasts'](arg1);
}

export function SearchSuggestions(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchSuggestions'](arg1, arg2, arg3);
}

export function SearchTracks(arg1) {
  return window['go']['main']['App']['SearchTracks'](arg1);
}

export function Seek(arg1) {
  return window['go']['main']['App']['Seek'](arg1);
}

export function SetLibraryMode(arg1) {
  return window['go']['main']['App']['SetLibraryMode'](arg1);
}

export function SetMusicRayContentMode(arg1) {
  return window['go']['main']['App']['SetMusicRayContentMode'](arg1);
}

export function SetMusicRaySaved(arg1, arg2) {
  return window['go']['main']['App']['SetMusicRaySaved'](arg1, arg2);
}

export function SetMusicRaySortMode(arg1) {
  return window['go']['main']['App']['SetMusicRaySortMode'](arg1);
}

export function SetNormalizePodcastVolume(arg1) {
  return window['go']['main']['App']['SetNormalizePodcastVolume'](arg1);
}

export function SetPodcastRayContentMode(arg1) {
  return window['go']['main']['App']['SetPodcastRayContentMode'](arg1);
}

export function SetPodcastRaySaved(arg1, arg2) {
  return window['go']['main']['App']['SetPodcastRaySaved'](arg1, arg2);
}

export function SetPodcastRaySortMode(arg1) {
  return window['go']['main']['App']['SetPodcastRaySortMode'](arg1);
}

export function SetVolume(arg1) {
  return window['go']['main']['App']['SetVolume'](arg1);
}

export function SetVolumePreview(arg1) {
  return window['go']['main']['App']['SetVolumePreview'](arg1);
}

export function SkipToTrackInQueue(arg1) {
  return window['go']['main']['App']['SkipToTrackInQueue'](arg1);
}

export function Snapshot() {
  return window['go']['main']['App']['Snapshot']();
}

export function TestEssentia(arg1) {
  return window['go']['main']['App']['TestEssentia'](arg1);
}

export function TestFFmpeg(arg1) {
  return window['go']['main']['App']['TestFFmpeg'](arg1);
}

export function TestMiniLM(arg1) {
  return window['go']['main']['App']['TestMiniLM'](arg1);
}

export function TestONNXRuntime(arg1) {
  return window['go']['main']['App']['TestONNXRuntime'](arg1);
}

export function TestYtDlp(arg1) {
  return window['go']['main']['App']['TestYtDlp'](arg1);
}

export function ToggleMute() {
  return window['go']['main']['App']['ToggleMute']();
}

export function TogglePause() {
  return window['go']['main']['App']['TogglePause']();
}

export function TogglePlay() {
  return window['go']['main']['App']['TogglePlay']();
}

export function UpdatePodcastProgress(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdatePodcastProgress'](arg1, arg2, arg3);
}
