// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {externalmedia} from '../models';
import {main} from '../models';
import {deps} from '../models';
import {emoflow} from '../models';
import {appstate} from '../models';
import {library} from '../models';
import {podcast} from '../models';
import {recommend} from '../models';
import {search} from '../models';

export function AddExternalLink(arg1:string,arg2:string):Promise<externalmedia.JobDTO>;

export function AddFiles():Promise<main.BootstrapPayload>;

export function AddFolder():Promise<main.BootstrapPayload>;

export function AddPodcastFiles():Promise<main.BootstrapPayload>;

export function AddPodcastFolder():Promise<main.BootstrapPayload>;

export function Bootstrap():Promise<main.BootstrapPayload>;

export function CancelExternalDownload(arg1:string):Promise<void>;

export function ChooseDirectory(arg1:string):Promise<string>;

export function ChooseFile(arg1:string,arg2:string):Promise<string>;

export function DebugReindexLibrary():Promise<main.DebugReindexResult>;

export function DeleteExternalItem(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function DeleteSavedMusicRay(arg1:string):Promise<main.BootstrapPayload>;

export function DoctorCheck(arg1:string,arg2:main.SettingsPayload):Promise<deps.Check>;

export function DoctorRepair(arg1:string,arg2:main.SettingsPayload):Promise<deps.RepairResult>;

export function GetCurrentEmoFlow():Promise<emoflow.UIState>;

export function GetExternalMediaSettings():Promise<externalmedia.Settings>;

export function GetPlaybackState():Promise<appstate.PlayerState>;

export function GetRayBuildState():Promise<appstate.RayBuildState>;

export function GetSettings():Promise<main.SettingsPayload>;

export function ImportPaths(arg1:Array<string>):Promise<library.ImportSummary>;

export function ImportPodcastPaths(arg1:Array<string>):Promise<podcast.ImportResult>;

export function ListExternalDownloadJobs(arg1:number):Promise<Array<externalmedia.JobDTO>>;

export function MovePodcastRayItem(arg1:number,arg2:number):Promise<main.BootstrapPayload>;

export function MoveQueueItem(arg1:string,arg2:number):Promise<main.BootstrapPayload>;

export function NextPodcast():Promise<main.BootstrapPayload>;

export function NextTrack():Promise<main.BootstrapPayload>;

export function OpenExternalSource(arg1:string):Promise<void>;

export function OpenPodcastRayHistory(arg1:string):Promise<main.BootstrapPayload>;

export function PlayPodcast(arg1:string):Promise<main.BootstrapPayload>;

export function PlayPodcastRayItem(arg1:string):Promise<main.BootstrapPayload>;

export function PlayTrack(arg1:string):Promise<main.BootstrapPayload>;

export function PlayTrackWithMode(arg1:string,arg2:string):Promise<main.BootstrapPayload>;

export function PreviousPodcast():Promise<main.BootstrapPayload>;

export function PreviousTrack():Promise<main.BootstrapPayload>;

export function RayAudit(arg1:string,arg2:string,arg3:number):Promise<recommend.RayAuditResult>;

export function RemoveFromQueue(arg1:string):Promise<main.BootstrapPayload>;

export function RemovePodcastRayItem(arg1:string):Promise<main.BootstrapPayload>;

export function ResumeRay(arg1:string):Promise<main.BootstrapPayload>;

export function ResumeSavedMusicRay(arg1:string):Promise<main.BootstrapPayload>;

export function RetryExternalDownload(arg1:string):Promise<void>;

export function RunReclusterSingleflight():Promise<void>;

export function SaveExternalMediaSettings(arg1:externalmedia.Settings):Promise<void>;

export function SaveSettings(arg1:main.SettingsPayload):Promise<main.BootstrapPayload>;

export function ScheduleRecluster():Promise<void>;

export function SearchPodcasts(arg1:string):Promise<Array<podcast.Item>>;

export function SearchSuggestions(arg1:string,arg2:string,arg3:number):Promise<Array<main.SearchSuggestion>>;

export function SearchTracks(arg1:string):Promise<Array<search.Result>>;

export function Seek(arg1:number):Promise<appstate.PlayerState>;

export function SetLibraryMode(arg1:string):Promise<main.BootstrapPayload>;

export function SetMusicRayContentMode(arg1:string):Promise<main.BootstrapPayload>;

export function SetMusicRaySaved(arg1:string,arg2:boolean):Promise<main.BootstrapPayload>;

export function SetMusicRaySortMode(arg1:string):Promise<main.BootstrapPayload>;

export function SetNormalizePodcastVolume(arg1:boolean):Promise<main.SettingsPayload>;

export function SetPodcastRayContentMode(arg1:string):Promise<main.BootstrapPayload>;

export function SetPodcastRaySaved(arg1:string,arg2:boolean):Promise<main.BootstrapPayload>;

export function SetPodcastRaySortMode(arg1:string):Promise<main.BootstrapPayload>;

export function SetVolume(arg1:number):Promise<appstate.PlayerState>;

export function SetVolumePreview(arg1:number):Promise<appstate.PlayerState>;

export function SkipToTrackInQueue(arg1:string):Promise<main.BootstrapPayload>;

export function Snapshot():Promise<main.BootstrapPayload>;

export function TestEssentia(arg1:main.SettingsPayload):Promise<main.EssentiaTestResult>;

export function TestFFmpeg(arg1:string):Promise<string>;

export function TestMiniLM(arg1:main.SettingsPayload):Promise<main.MiniLMTestResult>;

export function TestONNXRuntime(arg1:main.SettingsPayload):Promise<main.RuntimeTestResult>;

export function TestYtDlp(arg1:string):Promise<externalmedia.ToolCheckResult>;

export function ToggleMute():Promise<appstate.PlayerState>;

export function TogglePause():Promise<appstate.PlayerState>;

export function TogglePlay():Promise<appstate.PlayerState>;

export function UpdatePodcastProgress(arg1:string,arg2:number,arg3:number):Promise<podcast.Item>;
